### ISSUE TITLE
[홍수희] 5주차 Heap_And_Priority_Queue_And_Intervals

### ISSUE THREAD

**Issue by HongGuma** [AlgorithmReview-Organization-2/CodingReviewRepository#238]
## 🔨 알고리즘 문제!
<br>1번 문제 : 정답률 70% medium ) 451. Sort Characters By Frequency
<br>링크    : https://leetcode.com/problems/sort-characters-by-frequency/
<br>2번 문제 : Easy ) 2357. Make Array Zero by Subtracting Equal Amounts
<br>링크    : https://leetcode.com/problems/make-array-zero-by-subtracting-equal-amounts/
<br>

**Comment by JeYeongR** [comment]
2번 문제 이름이랑 링크가 달라요..! (제발 링크대로 갑시다..풀었음 ㅠㅠ)
