### ISSUE TITLE
[문상원] 4주차 Tree

### ISSUE THREAD

**Issue by desafin** [AlgorithmReview-Organization-2/CodingReviewRepository#350]
## 🔨 알고리즘 문제!
<br><br>1번 문제: 트리의 순회
<br>문제 링크: https://www.acmicpc.net/problem/2263
<br>관련 링크: 

<br><br>2번 문제: 트리
<br>문제 링크: https://www.acmicpc.net/problem/1068
<br>관련 링크: 

<br><br>3번 문제: 
<br>문제 링크: 
<br>관련 링크: 

<br><br>4번 문제: 
<br>문제 링크: 
<br>관련 링크: 

<br><br>5번 문제: 
<br>문제 링크: 
<br>관련 링크: 
<br>

**Comment by 724thomas** [comment]
@desafin 1번문제 중복인데, 다른 문제로 바꿔주세요~

**Comment by desafin** [comment]
> @desafin 1번문제 중복인데, 다른 문제로 바꿔주세요~

네 바꿨습니다~
