### ISSUE TITLE
[이성호] 4주차 Tree

### ISSUE THREAD

**Issue by dltjdgh0428** [AlgorithmReview-Organization-2/CodingReviewRepository#351]
## 🔨 알고리즘 문제!
<br><br>1번 문제: 트리나라 관광가이드
<br>문제 링크: https://www.acmicpc.net/problem/15805
<br>관련 링크: 

<br><br>2번 문제: 트리 순회
<br>문제 링크: https://www.acmicpc.net/problem/1991
<br>관련 링크: 

<br><br>3번 문제: 
<br>문제 링크: 
<br>관련 링크: 

<br><br>4번 문제: 
<br>문제 링크: 
<br>관련 링크: 

<br><br>5번 문제: 
<br>문제 링크: 
<br>관련 링크: 
<br>

**Comment by 724thomas** [comment]
1번 문제 중복이네요 다른 문제로 올려주세요

**Comment by dltjdgh0428** [comment]
네 수정 완료했습니다!
